const product = 1 * 2;
console.log(product);
console.log(typeof product);
const charge = 10;
const payment = 20;
const amountRemaining = payment - charge;
console.log(amountRemaining);
console.log(typeof amountRemaining);
const test = 2;
const assignments = 3;
const final = 4;
const grade = test + assignments + final;
console.log(grade);
console.log(typeof grade);
const fullName = 'Deion Balaan';
console.log(fullName);
console.log(typeof fullName);
const pH = 2;
const isAcidic = pH < 7;
console.log(isAcidic);
console.log(typeof isAcidic);
const numberOfSoldiers = 100;
const isSparta = numberOfSoldiers === 300;
console.log(isSparta);
console.log(typeof isSparta);
let nickname = fullName;
nickname += ' is the GOAT ';
console.log(nickname);
console.log(typeof nickname);
